import { NoteCategory, NotePriority } from '@/types';
import logger from '@/utils/logger';

export interface EnhancedNote {
  suggestedCategory: NoteCategory;
  suggestedPriority: NotePriority;
  suggestedTags: string[];
  extractedLinks: { url: string; title?: string }[];
  suggestedColor: string;
  readingTime: number;
  wordCount: number;
  autoGeneratedTitle?: string;
}

// Smart categorization based on content analysis
export function suggestCategory(content: string, title: string = ''): NoteCategory {
  const text = `${title} ${content}`.toLowerCase();

  // Keyword patterns for each category
  const patterns = {
    WORK: [
      'meeting', 'project', 'deadline', 'presentation', 'report', 'client', 'boss',
      'office', 'schedule', 'conference', 'email', 'document', 'proposal', 'budget',
      'strategy', 'target', 'goal', 'kpi', 'deadline', 'review', 'task', 'professional',
      'business', 'company', 'team', 'collaboration', 'management', 'planning', 'workflow'
    ],
    PERSONAL: [
      'family', 'friend', 'birthday', 'anniversary', 'gift', 'personal', 'home',
      'health', 'doctor', 'exercise', 'diet', 'shopping', 'personal', 'life',
      'relationship', 'home', 'personal development', 'self', 'routine', 'lifestyle'
    ],
    IDEAS: [
      'idea', 'innovate', 'creative', 'brainstorm', 'invention', 'concept',
      'design', 'creative', 'inspiration', 'invent', 'new', 'novel', 'unique',
      'startup', 'concept', 'prototype', 'solution', 'improvement'
    ],
    TASKS: [
      'todo', 'task', 'complete', 'finish', 'remember', 'call', 'buy', 'pay',
      'schedule', 'appointment', 'errand', 'chores', 'clean', 'organize',
      'fix', 'repair', 'setup', 'install', 'register', 'apply', 'submit'
    ]
  };

  // Score each category based on keyword matches
  const scores = {
    WORK: 0,
    PERSONAL: 0,
    IDEAS: 0,
    TASKS: 0,
    OTHER: 0
  };

  for (const [category, keywords] of Object.entries(patterns)) {
    for (const keyword of keywords) {
      if (text.includes(keyword)) {
        scores[category as keyof typeof scores] += 1;
      }
    }
  }

  // Find category with highest score
  let maxScore = 0;
  let suggestedCategory = 'OTHER';

  for (const [category, score] of Object.entries(scores)) {
    if (score > maxScore) {
      maxScore = score;
      suggestedCategory = category;
    }
  }

  return suggestedCategory as NoteCategory;
}

// Suggest priority based on content
export function suggestPriority(content: string, title: string = ''): NotePriority {
  const text = `${title} ${content}`.toLowerCase();

  // Urgent keywords
  const urgentKeywords = [
    'urgent', 'asap', 'emergency', 'critical', 'immediate', 'deadline',
    'important', 'priority', 'serious', 'rush', 'fast', 'quickly'
  ];

  // Low priority keywords
  const lowPriorityKeywords = [
    'whenever', 'eventually', 'someday', 'maybe', 'consider', 'think about',
    'optional', 'later', 'when possible', 'no rush', 'future'
  ];

  for (const keyword of urgentKeywords) {
    if (text.includes(keyword)) {
      return 'HIGH';
    }
  }

  for (const keyword of lowPriorityKeywords) {
    if (text.includes(keyword)) {
      return 'LOW';
    }
  }

  return 'MEDIUM';
}

// Extract tags from content
export function suggestTags(content: string, existingTags: string[] = []): string[] {
  const text = content.toLowerCase();
  const suggested: string[] = [];

  // Extract hashtags
  const hashtagRegex = /#(\w+)/g;
  const hashtags = text.match(hashtagRegex);
  if (hashtags) {
    hashtags.forEach(tag => {
      const cleanTag = tag.replace('#', '').trim();
      if (cleanTag.length > 0 && cleanTag.length <= 30 && !suggested.includes(cleanTag)) {
        suggested.push(cleanTag);
      }
    });
  }

  // Extract common words that could be tags
  const potentialTags = [
    'project', 'meeting', 'deadline', 'goal', 'target', 'review',
    'followup', 'action', 'decision', 'research', 'planning', 'design',
    'development', 'testing', 'deployment', 'launch', 'marketing', 'sales'
  ];

  for (const tag of potentialTags) {
    if (text.includes(tag) && !suggested.includes(tag) && !existingTags.includes(tag)) {
      suggested.push(tag);
    }
  }

  // Limit to 5 suggested tags
  return suggested.slice(0, 5);
}

// Extract URLs from content
export function extractLinks(content: string): Array<{ url: string; title?: string }> {
  const urlRegex = /(https?:\/\/[^\s]+)/g;
  const matches = content.match(urlRegex);
  const links: Array<{ url: string; title?: string }> = [];

  if (matches) {
    matches.forEach(url => {
      try {
        // Clean up URL (remove trailing punctuation)
        const cleanUrl = url.replace(/[.,;:]$/, '');
        links.push({ url: cleanUrl });
      } catch (error) {
        logger.warn('Invalid URL found:', url);
      }
    });
  }

  return links;
}

// Generate title from content if not provided
export function generateTitle(content: string): string {
  const sentences = content.split(/[.!?]/).filter(s => s.trim().length > 0);
  const firstSentence = sentences[0]?.trim() || '';

  // Take first 50 characters of first sentence
  let title = firstSentence.slice(0, 50);
  if (firstSentence.length > 50) {
    title += '...';
  }

  return title || 'Untitled Note';
}

// Detect duplicates
export function findPotentialDuplicates(content: string, existingNotes: Array<{ content: string }>): string[] {
  const potential: string[] = [];

  // Simple similarity check (can be enhanced with better algorithms)
  for (const note of existingNotes) {
    const similarity = calculateSimilarity(content, note.content);
    if (similarity > 0.7) { // 70% similarity threshold
      potential.push(note.content.slice(0, 100));
    }
  }

  return potential;
}

// Simple text similarity calculation
function calculateSimilarity(text1: string, text2: string): number {
  const words1 = text1.toLowerCase().split(/\s+/);
  const words2 = text2.toLowerCase().split(/\s+/);

  const intersection = words1.filter(word => words2.includes(word));
  const union = [...new Set([...words1, ...words2])];

  return intersection.length / union.length;
}

// Color suggestion based on category
export function suggestColor(category: NoteCategory): string {
  const categoryColors: Record<NoteCategory, string> = {
    WORK: '#3B82F6',        // Blue
    PERSONAL: '#10B981',    // Green
    IDEAS: '#8B5CF6',       // Purple
    TASKS: '#F59E0B',       // Orange
    OTHER: '#6B7280'        // Gray
  };

  return categoryColors[category] || '#FCD34D';
}

// Estimate reading time
export function calculateReadingTime(content: string): number {
  const words = content.trim().split(/\s+/).filter(word => word.length > 0);
  return Math.ceil(words.length / 200); // Average reading speed: 200 words/minute
}

// Validate content quality
export function validateContentQuality(content: string): { isValid: boolean; issues: string[] } {
  const issues: string[] = [];
  const trimmed = content.trim();

  // Minimum length check
  if (trimmed.length < 3) {
    issues.push('Content is too short');
  }

  // Maximum length check
  if (trimmed.length > 5000) {
    issues.push('Content is too long');
  }

  // Spam detection
  const words = trimmed.toLowerCase().split(/\s+/);
  const uniqueWords = new Set(words);

  if (words.length > 10 && uniqueWords.size < words.length * 0.3) {
    issues.push('Content appears to be repetitive');
  }

  // Check for excessive special characters
  const specialChars = trimmed.match(/[^\w\s]/g);
  if (specialChars && specialChars.length > trimmed.length * 0.5) {
    issues.push('Content contains too many special characters');
  }

  return {
    isValid: issues.length === 0,
    issues
  };
}

// Smart note enhancement
export function enhanceNote(content: string, title?: string): EnhancedNote {
  const enhanced: EnhancedNote = {
    suggestedCategory: suggestCategory(content, title || ''),
    suggestedPriority: suggestPriority(content, title || ''),
    suggestedTags: suggestTags(content),
    extractedLinks: extractLinks(content),
    suggestedColor: suggestColor(suggestCategory(content, title || '')),
    readingTime: calculateReadingTime(content),
    wordCount: content.trim().split(/\s+/).filter(word => word.length > 0).length,
    autoGeneratedTitle: (!title || title.trim().length === 0) ? generateTitle(content) : undefined,
  };

  return enhanced;
}