import { z } from 'zod';

// Custom validators
const urlValidator = z.string().refine(
  (url) => {
    try {
      new URL(url);
      return true;
    } catch {
      return false;
    }
  },
  { message: 'Invalid URL format' }
);

const hexColorValidator = z.string().regex(/^#[0-9A-F]{6}$/i, 'Invalid color format. Use HEX format like #FF5733');

const tagNameValidator = z.string().min(1).max(30).refine(
  (tag) => !tag.includes(',') && !tag.includes('#') && !tag.includes(' '),
  { message: 'Tags cannot contain commas, hashtags, or spaces' }
);

const checklistItemValidator = z.object({
  id: z.string().min(1),
  text: z.string().min(1).max(200, 'Checklist item must not exceed 200 characters'),
  completed: z.boolean().default(false),
  completedAt: z.date().optional(),
});

const noteLinkValidator = z.object({
  url: urlValidator,
  title: z.string().max(200).optional(),
  favicon: z.string().max(500).optional(),
});

// Content quality validator
const contentQualityValidator = z.string().refine(
  (content) => {
    const trimmed = content.trim();
    // Check for minimum meaningful content
    if (trimmed.length < 3) return false;

    // Check for excessive repetition (spam detection)
    const words = trimmed.toLowerCase().split(/\s+/);
    const uniqueWords = new Set(words);
    if (words.length > 10 && uniqueWords.size < words.length * 0.3) {
      return false; // Less than 30% unique words
    }

    return true;
  },
  { message: 'Content must be meaningful and not repetitive' }
);

// Smart schemas with enhanced validation
export const createQuickNoteSchema = z.object({
  title: z.string()
    .min(1, 'Title is required')
    .max(100, 'Title must not exceed 100 characters')
    .refine(title => title.trim().length > 0, { message: 'Title cannot be empty or just whitespace' }),

  content: contentQualityValidator,

  richContent: z.string().max(10000, 'Rich content must not exceed 10000 characters').optional(),

  category: z.enum(['PERSONAL', 'WORK', 'IDEAS', 'TASKS', 'OTHER'], {
    errorMap: () => ({ message: 'Invalid category. Must be one of: PERSONAL, WORK, IDEAS, TASKS, OTHER' })
  }).optional(),

  priority: z.enum(['LOW', 'MEDIUM', 'HIGH'], {
    errorMap: () => ({ message: 'Invalid priority. Must be one of: LOW, MEDIUM, HIGH' })
  }).optional(),

  color: hexColorValidator.optional(),

  tags: z.array(tagNameValidator)
    .min(0, 'Tags array cannot be negative')
    .max(15, 'Maximum 15 tags allowed')
    .refine(tags => new Set(tags).size === tags.length, {
      message: 'Duplicate tags are not allowed'
    })
    .optional(),

  suggestedTags: z.array(tagNameValidator).max(10).optional(),

  checklist: z.array(checklistItemValidator)
    .max(20, 'Maximum 20 checklist items allowed')
    .refine(items => new Set(items.map(i => i.id)).size === items.length, {
      message: 'Duplicate checklist item IDs are not allowed'
    })
    .optional(),

  links: z.array(noteLinkValidator)
    .max(10, 'Maximum 10 links allowed')
    .refine(links => new Set(links.map(l => l.url)).size === links.length, {
      message: 'Duplicate links are not allowed'
    })
    .optional(),

  isPinned: z.boolean().optional(),
  status: z.enum(['DRAFT', 'ACTIVE', 'COMPLETED']).optional(),

  templateId: z.string().optional(),
  folder: z.string().max(50).optional(),

  reminderDate: z.string().datetime('Invalid datetime format for reminderDate').optional(),
  dueDate: z.string().datetime('Invalid datetime format for dueDate').optional(),

  recurringPattern: z.enum(['NONE', 'DAILY', 'WEEKLY', 'MONTHLY']).optional(),

  sharedWith: z.array(z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid user ID format'))
    .max(20, 'Maximum 20 users allowed')
    .optional(),

  isPublic: z.boolean().optional(),

  location: z.object({
    latitude: z.number().min(-90).max(90).optional(),
    longitude: z.number().min(-180).max(180).optional(),
    placeName: z.string().max(100).optional(),
  }).optional(),

  metadata: z.object({
    source: z.enum(['web', 'mobile', 'api', 'import']).optional(),
    autoGenerated: z.boolean().optional(),
  }).optional(),
}).refine(
  (data) => {
    // Cross-field validation
    if (data.dueDate && data.reminderDate) {
      const dueDate = new Date(data.dueDate);
      const reminderDate = new Date(data.reminderDate);
      if (reminderDate > dueDate) {
        return false;
      }
    }
    return true;
  },
  { message: 'Reminder date must be before or equal to due date', path: ['reminderDate'] }
).refine(
  (data) => {
    // Validation for recurring notes
    if (data.recurringPattern && data.recurringPattern !== 'NONE' && !data.dueDate) {
      return false;
    }
    return true;
  },
  { message: 'Due date is required for recurring notes', path: ['dueDate'] }
);

export const updateQuickNoteSchema = z.object({
  title: z.string().min(1).max(100).optional(),
  content: contentQualityValidator.optional(),
  richContent: z.string().max(10000).optional(),
  category: z.enum(['PERSONAL', 'WORK', 'IDEAS', 'TASKS', 'OTHER']).optional(),
  priority: z.enum(['LOW', 'MEDIUM', 'HIGH']).optional(),
  color: hexColorValidator.optional(),
  tags: z.array(tagNameValidator).max(15).refine(tags => new Set(tags).size === tags.length, {
    message: 'Duplicate tags are not allowed'
  }).optional(),
  suggestedTags: z.array(tagNameValidator).max(10).optional(),
  checklist: z.array(checklistItemValidator).max(20).refine(items => new Set(items.map(i => i.id)).size === items.length, {
    message: 'Duplicate checklist item IDs are not allowed'
  }).optional(),
  links: z.array(noteLinkValidator).max(10).refine(links => new Set(links.map(l => l.url)).size === links.length, {
    message: 'Duplicate links are not allowed'
  }).optional(),
  isPinned: z.boolean().optional(),
  isArchived: z.boolean().optional(),
  status: z.enum(['DRAFT', 'ACTIVE', 'COMPLETED']).optional(),
  templateId: z.string().optional(),
  folder: z.string().max(50).optional(),
  reminderDate: z.string().datetime().optional(),
  dueDate: z.string().datetime().optional(),
  recurringPattern: z.enum(['NONE', 'DAILY', 'WEEKLY', 'MONTHLY']).optional(),
  completedAt: z.string().datetime().optional(),
  sharedWith: z.array(z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid user ID format')).max(20).optional(),
  isPublic: z.boolean().optional(),
  location: z.object({
    latitude: z.number().min(-90).max(90).optional(),
    longitude: z.number().min(-180).max(180).optional(),
    placeName: z.string().max(100).optional(),
  }).optional(),
}).refine(
  (data) => {
    if (data.dueDate && data.reminderDate) {
      const dueDate = new Date(data.dueDate);
      const reminderDate = new Date(data.reminderDate);
      if (reminderDate > dueDate) {
        return false;
      }
    }
    return true;
  },
  { message: 'Reminder date must be before or equal to due date', path: ['reminderDate'] }
);

export const quickNoteQuerySchema = z.object({
  category: z.enum(['PERSONAL', 'WORK', 'IDEAS', 'TASKS', 'OTHER']).optional(),
  priority: z.enum(['LOW', 'MEDIUM', 'HIGH']).optional(),
  status: z.enum(['DRAFT', 'ACTIVE', 'COMPLETED']).optional(),
  isArchived: z.enum(['true', 'false']).optional(),
  isPinned: z.enum(['true', 'false']).optional(),
  folder: z.string().optional(),
  tags: z.string().optional(),
  search: z.string().min(1).max(100).optional(),
  sortBy: z.enum(['priority', 'reminder', 'due', 'title', 'created', 'updated', 'checklist']).optional(),
  reminderDue: z.enum(['today', 'upcoming', 'overdue']).optional(),
  dueDate: z.enum(['today', 'upcoming', 'overdue']).optional(),
  templateId: z.string().optional(),
  page: z.string().optional(),
  limit: z.string().optional(),
});

// Checklist operations
export const checklistItemSchema = z.object({
  text: z.string().min(1).max(200),
});

export const toggleChecklistItemSchema = z.object({
  completed: z.boolean(),
});

export const bulkActionSchema = z.object({
  action: z.enum(['archive', 'unarchive', 'delete', 'pin', 'unpin', 'complete', 'restore']),
  noteIds: z.array(z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid note ID format'))
    .min(1, 'At least one note ID required')
    .max(50, 'Maximum 50 notes per bulk action'),
});

export type CreateQuickNoteInput = z.infer<typeof createQuickNoteSchema>;
export type UpdateQuickNoteInput = z.infer<typeof updateQuickNoteSchema>;
export type QuickNoteQueryInput = z.infer<typeof quickNoteQuerySchema>;
export type ChecklistItemInput = z.infer<typeof checklistItemSchema>;
export type ToggleChecklistItemInput = z.infer<typeof toggleChecklistItemSchema>;
export type BulkActionInput = z.infer<typeof bulkActionSchema>;
