import mongoose, { Schema, Document, Types } from 'mongoose';

export type NotePriority = 'LOW' | 'MEDIUM' | 'HIGH';
export type NoteCategory = 'PERSONAL' | 'WORK' | 'IDEAS' | 'TASKS' | 'OTHER';
export type NoteStatus = 'DRAFT' | 'ACTIVE' | 'COMPLETED';
export type RecurringPattern = 'NONE' | 'DAILY' | 'WEEKLY' | 'MONTHLY';

export interface IChecklistItem {
  id: string;
  text: string;
  completed: boolean;
  completedAt?: Date;
}

export interface INoteLink {
  url: string;
  title?: string;
  favicon?: string;
}

export interface IQuickNote extends Document {
  userId: Types.ObjectId;
  title: string;
  content: string;
  richContent?: string; // HTML content for rich text editor
  category: NoteCategory;
  priority: NotePriority;
  color: string;
  tags: string[];
  suggestedTags?: string[]; // AI-suggested tags
  checklist: IChecklistItem[]; // Subtasks/checklist
  links: INoteLink[]; // Extracted URLs from content
  isPinned: boolean;
  isArchived: boolean;
  status: NoteStatus; // DRAFT, ACTIVE, COMPLETED
  templateId?: string; // If created from a template
  folder?: string; // Organization folder
  reminderDate?: Date;
  dueDate?: Date; // Separate due date from reminder
  recurringPattern?: RecurringPattern;
  completedAt?: Date;
  sharedWith?: Types.ObjectId[]; // Users this note is shared with
  isPublic?: boolean; // Public visibility
  location?: {
    latitude?: number;
    longitude?: number;
    placeName?: string;
  };
  metadata: {
    source?: 'web' | 'mobile' | 'api' | 'import';
    autoGenerated?: boolean;
    wordCount?: number;
    readingTime?: number; // minutes
    lastAutoSaved?: Date;
    duplicateOf?: Types.ObjectId;
    relatedNotes?: Types.ObjectId[];
  };
  createdAt: Date;
  updatedAt: Date;
}

const QuickNoteSchema = new Schema<IQuickNote>(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 100,
    },
    content: {
      type: String,
      required: true,
      trim: true,
      maxlength: 5000,
    },
    richContent: {
      type: String,
      maxlength: 10000,
    },
    category: {
      type: String,
      enum: ['PERSONAL', 'WORK', 'IDEAS', 'TASKS', 'OTHER'],
      default: 'OTHER',
      index: true,
    },
    priority: {
      type: String,
      enum: ['LOW', 'MEDIUM', 'HIGH'],
      default: 'MEDIUM',
      index: true,
    },
    color: {
      type: String,
      default: '#FCD34D',
    },
    tags: {
      type: [String],
      default: [],
      index: true,
    },
    suggestedTags: {
      type: [String],
      default: [],
    },
    checklist: [{
      id: {
        type: String,
        required: true,
      },
      text: {
        type: String,
        required: true,
        maxlength: 200,
      },
      completed: {
        type: Boolean,
        default: false,
      },
      completedAt: Date,
    }],
    links: [{
      url: {
        type: String,
        required: true,
      },
      title: String,
      favicon: String,
    }],
    isPinned: {
      type: Boolean,
      default: false,
      index: true,
    },
    isArchived: {
      type: Boolean,
      default: false,
      index: true,
    },
    status: {
      type: String,
      enum: ['DRAFT', 'ACTIVE', 'COMPLETED'],
      default: 'ACTIVE',
      index: true,
    },
    templateId: String,
    folder: {
      type: String,
      index: true,
    },
    reminderDate: {
      type: Date,
      index: true,
    },
    dueDate: {
      type: Date,
      index: true,
    },
    recurringPattern: {
      type: String,
      enum: ['NONE', 'DAILY', 'WEEKLY', 'MONTHLY'],
      default: 'NONE',
    },
    completedAt: Date,
    sharedWith: [{
      type: Schema.Types.ObjectId,
      ref: 'User',
    }],
    isPublic: {
      type: Boolean,
      default: false,
    },
    location: {
      latitude: Number,
      longitude: Number,
      placeName: String,
    },
    metadata: {
      source: {
        type: String,
        enum: ['web', 'mobile', 'api', 'import'],
      },
      autoGenerated: Boolean,
      wordCount: Number,
      readingTime: Number,
      lastAutoSaved: Date,
      duplicateOf: {
        type: Schema.Types.ObjectId,
        ref: 'QuickNote',
      },
      relatedNotes: [{
        type: Schema.Types.ObjectId,
        ref: 'QuickNote',
      }],
    },
  },
  {
    timestamps: true,
  }
);

// Compound indexes for efficient queries
QuickNoteSchema.index({ userId: 1, isArchived: 1, isPinned: 1 });
QuickNoteSchema.index({ userId: 1, category: 1 });
QuickNoteSchema.index({ userId: 1, priority: 1 });
QuickNoteSchema.index({ userId: 1, tags: 1 });
QuickNoteSchema.index({ userId: 1, status: 1 });
QuickNoteSchema.index({ userId: 1, folder: 1 });
QuickNoteSchema.index({ userId: 1, dueDate: 1 });
QuickNoteSchema.index({ createdAt: -1 });

// Text search index
QuickNoteSchema.index({ title: 'text', content: 'text' });

// Virtual for checklist completion percentage
QuickNoteSchema.virtual('checklistProgress').get(function(this: IQuickNote) {
  if (this.checklist.length === 0) return 0;
  const completed = this.checklist.filter(item => item.completed).length;
  return Math.round((completed / this.checklist.length) * 100);
});

// Pre-save middleware for auto-tagging and word count
QuickNoteSchema.pre('save', function(next) {
  if (this.isModified('content')) {
    // Calculate word count
    const words = this.content.trim().split(/\s+/).filter(word => word.length > 0);
    this.metadata.wordCount = words.length;
    this.metadata.readingTime = Math.ceil(words.length / 200); // Average reading speed
  }
  next();
});

export default mongoose.model<IQuickNote>('QuickNote', QuickNoteSchema);
